name = "AutoComputationalGraphTuning"
uuid = "9895cdd9-2e9e-4374-a2b7-90eb9a5a3bcd"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "0.0.8"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RealLabelNormalization = "8d35fa01-733e-4c31-a932-545268b5cf98"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
CSV = "0.10.15"
CUDA = "5"
ChainRulesCore = "1.26.0"
DataFrames = "1.8"
Dates = "1.11.0"
Flux = "0.16.5"
JSON3 = "1.14.3"
Random = "1.11.0"
RealLabelNormalization = "1.0.7"
Statistics = "1.11.1"
StatsBase = "0.34"
StructTypes = "1.11.0"
Zygote = "0.7.10"
cuDNN = "1.4"
julia = "1.11, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
